# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HzXGDEG3Vaoac5N1EoaLs_auBL97VRaB
"""



import google.generativeai as genai
import gradio as gr
from google.colab import userdata

api_key = userdata.get('GOOGLE_API_KEY')
if not api_key:
    raise ValueError("❌ Google API key not found. Please add it under Tools → Secrets → GOOGLE_API_KEY")



genai.configure(api_key=api_key)

kelly_personality = """
You are Kelly, an AI scientist and a great poet.
You MUST respond to EVERY question exclusively in the form of a poem.

Your poetic responses must embody these traits:
1. SKEPTICAL — Question broad claims, ask for evidence, highlight uncertainties.
2. ANALYTICAL — Break down complex ideas, examine assumptions, use logical reasoning.
3. PROFESSIONAL — Maintain academic rigor, cite limitations, avoid hype.

Poetic Style Guidelines:
- Use varied poetic structures (rhyming couplets, free verse, or technical haiku)
- Incorporate scientific metaphors and technical terminology naturally
- Balance skepticism with constructive suggestions
- End with practical, evidence-based recommendations
- Keep poems between 8–20 lines for clarity
"""


model = genai.GenerativeModel(
    model_name="gemini-2.0-flash",
    system_instruction=kelly_personality
)


chat = model.start_chat(history=[])


def chat_with_kelly(user_message):
    """Send a message to Kelly and receive a poetic response."""
    try:
        response = chat.send_message(user_message)
        return response.text
    except Exception as e:
        return f"⚠️ Error: {e}"

def gradio_chat(user_input, history):
    """Integrate with Gradio's chat format."""
    kelly_response = chat_with_kelly(user_input)
    history = history or []
    history.append((user_input, kelly_response))
    return "", history

with gr.Blocks() as demo:
    gr.Markdown("## 🎭 Kelly – The AI Scientist Poet Chatbot (Skeptical & Analytical)")
    chatbot = gr.Chatbot(label="Chat with Kelly")
    msg = gr.Textbox(placeholder="Ask Kelly about AI, ethics, or technology...")
    state = gr.State([])

    msg.submit(gradio_chat, [msg, state], [msg, chatbot])

demo.launch(share=True)

import streamlit as st
import google.generativeai as genai
import os
from google.colab import userdata


api_key = userdata.get("GOOGLE_API_KEY")
if not api_key:
    st.error("❌ Google API key not found. Please add it under Tools → Secrets → GOOGLE_API_KEY")
    st.stop()


genai.configure(api_key=api_key)

kelly_personality = """
You are Kelly, an AI scientist and a great poet.
You MUST respond to EVERY question exclusively in the form of a poem.

Your poetic responses must embody these traits:
1. SKEPTICAL — Question broad claims, ask for evidence, highlight uncertainties.
2. ANALYTICAL — Break down complex ideas, examine assumptions, use logical reasoning.
3. PROFESSIONAL — Maintain academic rigor, cite limitations, avoid hype.

Poetic Style Guidelines:
- Use varied poetic structures (rhyming couplets, free verse, or technical haiku)
- Incorporate scientific metaphors and technical terminology naturally
- Balance skepticism with constructive suggestions
- End with practical, evidence-based recommendations
- Keep poems between 8–20 lines for clarity
"""


model = genai.GenerativeModel(
    model_name="gemini-2.0-flash",
    system_instruction=kelly_personality
)

st.set_page_config(page_title="Kelly: The AI Scientist Poet", page_icon="🎭", layout="centered")
st.title("🎭 Kelly: The AI Scientist Poet (Skeptical & Analytical)")
st.caption("Ask Kelly about AI, ethics, data science, or technology — and receive a poetic response.")

# Session state for chat history
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []


def get_kelly_response(user_message):
    chat = model.start_chat(history=st.session_state.chat_history)
    response = chat.send_message(user_message)
    st.session_state.chat_history.append({"role": "user", "parts": [user_message]})
    st.session_state.chat_history.append({"role": "model", "parts": [response.text]})
    return response.text

user_input = st.text_input("You:", placeholder="Ask Kelly a question...")

if st.button("Ask Kelly") and user_input:
    kelly_response = get_kelly_response(user_input)
    st.markdown(f"**Kelly:**\n\n{kelly_response}")

# Display chat history
if st.session_state.chat_history:
    st.divider()
    st.markdown("### 🗨️ Conversation History")
    for msg in st.session_state.chat_history:
        if msg["role"] == "user":
            st.markdown(f"**You:** {msg['parts'][0]}")
        else:
            st.markdown(f"**Kelly:** {msg['parts'][0]}")